#!/bin/sh

me=`basename $0`

echo "DEBUG: picklistops argv[$#] = $@" >&2
echo "DEBUG: PPD: $PPD" >&2
echo "DEBUG: me: $me" >&2


. /etc/picklister-wm.conf

job="$1"
user="$2"
name="$3"
copies="$4"
options="$5"
data="$6"

[ -n "$data" ] && exec <$data

workdir=`mktemp --tmpdir --directory picklist.XXXXXXXXXX`

# dos2unix
work_orders=$(
	cat | tee ${workdir}/orig | /usr/local/bin/picklister parse \
		--print %W \
		--exec "/usr/local/bin/picklister watermark \
				--text=\"${WM_TEXT}\" \
				--output=${workdir}/%W-%n-%I.png %W %I \
				--path=\"${WM_IMAGES}\"" \
		--output ${workdir}/%W-0-report.txt
)
wait

#for f in ${workdir}/*.txt; do
#	base=`basename $f .txt`
#	enscript --quiet --no-header --output ${workdir}/${base}.ps $f &
#done
#wait

for f in ${workdir}/*.png; do
	base=`basename $f .png`
	unset input_options
	unset output_options
	output_options="$output_options -units PixelsPerInch"
	output_options="$output_options -gravity center"
	output_options="$output_options -background white"
	output_options="$output_options -adaptive-resize 4590x"
	output_options="$output_options -adaptive-resize x5940>"
	output_options="$output_options -density 600"
	#output_options="$output_options -resize 2295x>"
	#output_options="$output_options -resize x2970>"
	#output_options="$output_options -density 300"
	#convert $input_options $f $output_options ${workdir}/${base}.ps
	nice convert $input_options $f $output_options ${workdir}/${base}.pcl &
done
wait

case `basename $0` in
 *tops)  filter=ps2ps ;;
 *topdf) filter=ps2pdf ;;
 *)      filter=ps2ps ;;
esac

#for wo in $work_orders; do
#	cat `ls ${workdir}/${wo}-*.ps`
#done | ps2pdf - - > ${wo}.pdf

#for wo in $work_orders; do
#	cat `ls ${workdir}/${wo}-*.ps`
#done | $filter - -

#remove leading and trailing PCL resets
sed -i 's/^\x1bE//' ${workdir}/*.pcl
sed -i 's/\x1bE$/\x0c/' ${workdir}/*.pcl

#echo '\033E\033&l1S'  # reset duplex
#echo '\033&k2G'       # FF = CR+FF
for wo in $work_orders; do
	echo '\033E\033&l1S'  # reset duplex
	echo '\033&k2G'       # FF = CR+FF
	#echo '\033&a1G'  # select next front face
	cat `ls ${workdir}/${wo}-*.txt`
	echo '\033&a0G'  # select next face
	cat `ls ${workdir}/${wo}-*.pcl`
done #| $filter - -

rm -rf $workdir
